name: Build .NET Framework 4.8 Project

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t my-dotnet-framework-image .

    - name: Run build in Docker
      run: |
        docker run --rm my-dotnet-framework-image nuget restore SiapControl.sln
        docker run --rm my-dotnet-framework-image msbuild SiapControl.sln /p:Configuration=Release
